name: "HOBEIAN for Zigbee2mqtt"
version: "1.0.1"
slug: "hobeian-for-zigbee-2mqtt"
description: "HOBEIAN brand upgrade, suitable for Zigbee2MQTT version iteration, Zigbee 3.0 new product adaptation"
url: "https://github.com/waxgourd-ha/hobeian-addons"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
init: false
image: "wghaos/hobeian-for-zigbee2mqtt"
privileged:
  - SYS_ADMIN
docker_api: true
hassio_api: true
hassio_role: manager
auth_api: true
